### ISSUE TITLE
Enable code obfuscation mechanism, paypal checkout sdk does not work normally

### ISSUE THREAD

**Issue by panguojian** [paypal/android-checkout-sdk#17] opened 2021-06-19 10:27 UTC
Enable code obfuscation mechanism, paypal checkout sdk does not work normally

**Comment by tdchow** [comment] 2021-06-21 19:43
Hey @panguojian. Thanks for reporting this. Would you be able to provide additional information?
* Which obfuscation tool are you using? (proguard, R8)
* What issue are you seeing with the Checkout SDK?

**Comment by tdchow** [comment] 2021-07-06 14:58
Closing due to inactivity.

**Comment by nazarabd3005** [comment] 2022-03-28 12:53
Hi @tdchow currently using the latest version (0.6.1) with obfuscation (proguard), getting crashes when starting the app

**Comment by ndmunoz10** [comment] 2022-03-28 22:01
Hi @nazarabd3005, thanks for letting us know. What issue or crash are you seeing with our SDK?

**Comment by nazarabd3005** [comment] 2022-03-28 22:20
find the log here:
`2022-03-29 05:11:03.842 23558-23558/com.forest_interactive.walletcodes.b2c.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.forest_interactive.walletcodes.b2c.dev, PID: 23558
    java.lang.ExceptionInInitializerError
        at com.paypal.pyplcheckout.di.AppModule.providesEncryptedSharedPrefs$pyplcheckout_externalRelease(SourceFile:85)
        at com.paypal.pyplcheckout.di.AppModule_ProvidesEncryptedSharedPrefs$pyplcheckout_externalReleaseFactory.providesEncryptedSharedPrefs$pyplcheckout_externalRelease(SourceFile:43)
        at com.paypal.pyplcheckout.di.AppModule_ProvidesEncryptedSharedPrefs$pyplcheckout_externalReleaseFactory.get(SourceFile:33)
        at com.paypal.pyplcheckout.di.AppModule_ProvidesEncryptedSharedPrefs$pyplcheckout_externalReleaseFactory.get(SourceFile:13)
        at com.paypal.pyplcheckout.utils.AmplitudeUtils_Factory.get(SourceFile:39)
        at com.paypal.pyplcheckout.utils.AmplitudeUtils_Factory.get(SourceFile:12)
        at com.paypal.pyplcheckout.di.AppModule_ProvidesAmplitudeInitializer$pyplcheckout_externalReleaseFactory.get(SourceFile:42)
        at com.paypal.pyplcheckout.di.AppModule_ProvidesAmplitudeInitializer$pyplcheckout_externalReleaseFactory.get(SourceFile:15)
        at cg.b.get(SourceFile:47)
        at com.paypal.pyplcheckout.instrumentation.AmplitudeManager_Factory.get(SourceFile:37)
        at com.paypal.pyplcheckout.instrumentation.AmplitudeManager_Factory.get(SourceFile:13)
        at cg.b.get(SourceFile:47)
        at com.paypal.pyplcheckout.di.DaggerSdkComponent.getAmplitudeManager(SourceFile:473)
        at com.paypal.checkout.PayPalCheckout.setConfig(SourceFile:72)
        at com.forest_interactive.walletcodes.b2c.base.BaseApplication.k(SourceFile:136)
        at com.forest_interactive.walletcodes.b2c.base.BaseApplication.onCreate(SourceFile:94)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
        at android.app.ActivityThread.access$1500(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.RuntimeException: Field keySize_ for com.google.crypto.tink.proto.u not found. Known fields are [private int com.google.crypto.tink.proto.u.v, private static final com.google.crypto.tink.proto.u com.google.crypto.tink.proto.u.w, private static volatile com.google.crypto.tink.shaded.protobuf.z0 com.google.crypto.tink.proto.u.x]
        at com.google.crypto.tink.shaded.protobuf.t0.n0(SourceFile:608)
        at com.google.crypto.tink.shaded.protobuf.t0.T(SourceFile:502)
        at com.google.crypto.tink.shaded.protobuf.t0.R(SourceFile:221)
        at com.google.crypto.tink.shaded.protobuf.i0.e(SourceFile:85)
        at com.google.crypto.tink.shaded.protobuf.i0.a(SourceFile:71)
        at com.google.crypto.tink.shaded.protobuf.c1.d(SourceFile:93)
        at com.google.crypto.tink.shaded.protobuf.c1.e(SourceFile:107)
        at com.google.crypto.tink.shaded.protobuf.y.B(SourceFile:171)
        at com.google.crypto.tink.shaded.protobuf.y$a.s(SourceFile:391)
        at com.google.crypto.tink.shaded.protobuf.y$a.r(SourceFile:399)
        at xc.a.k(SourceFile:131)
        at xc.a.j(SourceFile:114)
        at androidx.security.crypto.a$d.<clinit>(SourceFile:179)`

**Comment by tdchow** [comment] 2022-03-31 15:58
Hey @nazarabd3005! Thanks for sharing the stacktrace. 

Adding this additional rule to your app module's `proguard-rules.pro` file should fix the crash:
```
-keep class com.google.crypto.tink.** { *; }
```

We'll update the proguard rules for the SDK in the next release. But this should unblock you for now!

**Comment by nazarabd3005** [comment] 2022-04-14 05:26
Hey @tdchow Thanks for the update

**Comment by tdchow** [comment] 2022-04-14 14:35
@nazarabd3005 - No worries at all! Going to close the issue out. Please report here if you're still seeing obfuscation/minification issues.

**Closed by tdchow** 2022-04-14 14:35 UTC
Labels: 🚧 in-triage
