### ISSUE TITLE
Crash starting Paypal Button

### ISSUE THREAD

**Issue by SerggioC** [paypal/android-checkout-sdk#90] opened 2022-02-17 11:45 UTC
Paypal SDK version 0.6.0
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.paypal.checkout.fundingeligibility.FundingEligibilityItem com.paypal.checkout.fundingeligibility.FundingEligibilityItems.getPaypal()' on a null object reference
        at com.paypal.checkout.paymentbutton.PaymentButton.updateEligibilityStatus(PaymentButton.kt:270)
        at com.paypal.checkout.paymentbutton.PaymentButton.access$updateEligibilityStatus(PaymentButton.kt:51)
        at com.paypal.checkout.paymentbutton.PaymentButton$eligibilityEventListener$1.onEvent(PaymentButton.kt:64)
        at com.paypal.pyplcheckout.events.Events.fire(Events.java:123)
        at com.paypal.checkout.PayPalCheckout$retrieveFundingEligibility$1.invokeSuspend(PayPalCheckout.kt:201)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
```

**Comment by maltsev-gorskij** [comment] 2022-02-17 14:35
> ```
> E/InstrumentationErr: Encountered an com.google.gson.JsonSyntaxException with message: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 11 path $.error null
>     com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 11 path $.error
>         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
>         at com.google.gson.Gson.fromJson(Gson.java:963)
>         at com.google.gson.Gson.fromJson(Gson.java:901)
>         at com.paypal.checkout.fundingeligibility.RetrieveFundingEligibilityAction$retrieve$3$await$$inlined$suspendCancellableCoroutine$lambda$1.onResponse(NetworkExtensions.kt:31)
>         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:920)
>      Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 11 path $.error
>         at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
>         at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
>         at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
>         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
>         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
>         at com.google.gson.Gson.fromJson(Gson.java:963) 
>         at com.google.gson.Gson.fromJson(Gson.java:901) 
>         at com.paypal.checkout.fundingeligibility.RetrieveFundingEligibilityAction$retrieve$3$await$$inlined$suspendCancellableCoroutine$lambda$1.onResponse(NetworkExtensions.kt:31) 
>         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
>         at java.lang.Thread.run(Thread.java:920) 
> ```

Same error on versions 0.3.0.
Appeared today and before that everything was alright.

**Comment by tdchow** [comment] 2022-02-17 15:35
Hi @SerggioC - Could you share code snippets of your integration? Also, do you have repo steps for both crashes?

@maltsev-gorskij - Was everything working before on version 0.3.0? And now you're seeing that crash without any app changes? This looks like something might have been changed on a backend API 😞

**Comment by maltsev-gorskij** [comment] 2022-02-17 15:54
> 



> Hi @SerggioC - Could you share code snippets of your integration? Also, do you have repo steps for both crashes?
> 
> @maltsev-gorskij - Was everything working before on version 0.3.0? And now you're seeing that crash without any app changes? This looks like something might have been changed on a backend API 😞

Hallo @tdchow 

I am currenty in the finish step of integration of paypal checkout sdk in app, in which min api level must be 21 and can't be rised. So i'm stuck at 0.3.0 version. 

I have integrated paypal sucessfully and for, maybe, two weeks everything was alright. I'have completing other parts of logic, indenendent from paypal. And for last three days it was just polishing. 

Yesterday in the evening i've checked, thats app started successfully multiple times and paypal payment was sucessfully done in sanbox also multiple time. 

Today, the first time a run the app, this error appear at the first moments when app is installed and passed the splashscreen and started rendering initial activity. 

Error appearing from time to time. But if i completely clean all build files and perform clean app rebuild - everything is alright. 

If i try to run app from android studio again second time after clean build - crash with this error. Trying to perform clean build, first start is ok, second - crash. 

From yesterdays successful app run, in my code nothing changed, but i'm still struggling with this error. 

Tried to run in different AVD with different Android versions, rollbacking to older stable commits, tried different versions of paypal checkout sdk. Nothing changes. 

Must note, thats this error exectly because of paypal sdk. Disabling dependency and commentin corresponding code solving the problem. But.. this is not what i want for now :)))

**Comment by tdchow** [comment] 2022-02-17 16:00
Hey @maltsev-gorskij

One clarification to make about API 21 support. We had issues with API 21 and 22 even on SDK versions 0.3.0 and earlier. 0.3.0 and later marked integrating functions as requiring API 23 and up, however the SDK still has a minimum API level of 21. So you'll be able to use the latest versions in your app. However, you'll want to do an API level check where you invoke the PayPal SDK and properly handle the API 21 and 22 case. 

The other issue sounds like something changed on the backend 😞  I'm still looking into this. Would you be able to share snippets of your integration? I'd like to reproduce the crash on my end. Thanks!

**Comment by SerggioC** [comment] 2022-02-17 17:43
Hi @tdchow,

I can't reproduce the issue anymore. Seems to be solved. Probably something changed in the data structure.

Anyway my implementation is: 
```
            val config = CheckoutConfig(
                application = application,
                clientId = BuildConfig.PCID,
                environment = if (BuildConfig.DEBUG) Environment.SANDBOX else Environment.LIVE,
                returnUrl = BuildConfig.APPLICATION_ID + "://paypalpay",
                currencyCode = CurrencyCode.EUR,
                userAction = UserAction.PAY_NOW,
                paymentButtonIntent = PaymentButtonIntent.CAPTURE,
                settingsConfig = SettingsConfig(
                    loggingEnabled = false,
                    shouldFailEligibility = false
                ),
            )
            PayPalCheckout.setConfig(config)

            try {
                buttonPayPal?.onEligibilityStatusChanged = { status: PaymentButtonEligibilityStatus ->
                    buttonPayPalFake?.isVisible = status == PaymentButtonEligibilityStatus.Eligible
                    progressBarPaypal?.isVisible = status == PaymentButtonEligibilityStatus.Loading
                }
            } catch (e: Exception) {
                Logger.e(e)
                progressBarPaypal?.isVisible = false
            }

            buttonPayPalFake?.setOnClickListener {
                getPayPayPalOrderIdFromAPI { orderID ->
                    buttonPayPal?.setup(CreateOrder { createOrderActions: CreateOrderActions ->
                        createOrderActions.set(orderID)
                    },
                        onApprove = OnApprove.invoke {
///                            wait for payment confirmation from backend... 
                        },
                        onCancel = OnCancel { payPalCanceled() },
                        onError = OnError { error -> payPalError(error) }
                    )
                    buttonPayPal?.performClick()
                }
            }
```

**Comment by tdchow** [comment] 2022-02-17 19:46
@SerggioC - Thanks for following up! And glad that the issue was resolved. There are a few improvements we can make in the SDK to prevent this unexpected response from crashing. We hope to have these changes in the next release.

One suggestion I'd make to your current integration is to set the config inside of your Application's `onCreate` function. As this should really only be set one time, and this will help the SDK recover if the process ends up getting destroyed in the background. See: https://developer.paypal.com/sdk/in-app/android/#link-configurethesdk

**Comment by maltsev-gorskij** [comment] 2022-02-17 20:20
> Hey @maltsev-gorskij
> 
> One clarification to make about API 21 support. We had issues with API 21 and 22 even on SDK versions 0.3.0 and earlier. 0.3.0 and later marked integrating functions as requiring API 23 and up, however the SDK still has a minimum API level of 21. So you'll be able to use the latest versions in your app. However, you'll want to do an API level check where you invoke the PayPal SDK and properly handle the API 21 and 22 case.
> 
> The other issue sounds like something changed on the backend 😞 I'm still looking into this. Would you be able to share snippets of your integration? I'd like to reproduce the crash on my end. Thanks!

Wow, thats amazing. So i can use leter version, but only new features requires new api level! 
Thats wasn't clear enough for me by reading patch notes for releases. Thank you!

Thats required my integration code snippets:

Application class

`
    private void configurePayPalSDK() {
        CheckoutConfig checkoutConfig = new CheckoutConfig(
                this,
                BuildConfig.PAYPAL_CLIENT_ID,
                Environment.SANDBOX,
                BuildConfig.APPLICATION_ID + "://paypalpay",
                null,
                UserAction.PAY_NOW
        );

        PayPalCheckout.setConfig(checkoutConfig);
    }
`

And calling paypal checkout sdk programmatically

`
    private fun initNativePayPalPayment(costAmount: String) {
        val order = CreateOrder { createOrderActions: CreateOrderActions ->
            val order = Order(
                intent = OrderIntent.CAPTURE,
                appContext = AppContext(userAction = UserAction.PAY_NOW),
                purchaseUnitList = listOf(
                    PurchaseUnit(
                        amount = Amount(currencyCode = CurrencyCode.USD, value = costAmount)
                    )
                )
            )

            createOrderActions.create(order)
        }

        val approve = OnApprove { approval: Approval ->
            val resultIntent = Intent().apply {
                // placing data in resultIntent
            }

            approval.orderActions.capture { captureOrderResult: CaptureOrderResult ->
                when (captureOrderResult) {
                    is CaptureOrderResult.Success -> {
                         // placing data in resultIntent
                    }
                    is CaptureOrderResult.Error -> {
                          // placing data in resultIntent
                    }
                }

                setResult(Activity.RESULT_OK, resultIntent)
                finish()
            }
        }

        val cancel = OnCancel {
            val resultIntent = Intent().apply {
                 // placing data in resultIntent
            }

            setResult(Activity.RESULT_OK, resultIntent)
            finish()
        }

        val error = OnError { errorInfo: ErrorInfo ->
            flProgressBar.visibility = View.VISIBLE
            val resultIntent = Intent().apply {
                  // placing data in resultIntent
            }

            setResult(Activity.RESULT_OK, resultIntent)
            finish()
        }

        PayPalCheckout.start(
            createOrder = order,
            onApprove = approve,
            onCancel = cancel,
            onError = error
        )
    }
`

**Comment by tdchow** [comment] 2022-02-17 20:33
@maltsev-gorskij - No problem! Apologies for the unclear release notes! I'll see if we can update those to make these changes clearer!

@SerggioC - I'm going to go ahead and close this issue out, as the original crashes were resolved. However, we'll still plan to handle the error case if the backend schema ends up changing on us. Thanks!

**Closed by tdchow** 2022-02-17 20:33 UTC
Labels: 🐞 bug
