### ISSUE TITLE
Google play warning: SDK “com.paypal.android.sdk:data-collector” collects device location without verification of user consent.

### ISSUE THREAD

**Issue by powerzd** [paypal/android-checkout-sdk#282] opened 2023-12-13 03:39 UTC
Google play says our app contains the SDK "com.paypal.android.sdk:data-collector", or contains a library that depends on the SDK, and the SDK is not verified Whether device location information is automatically collected with user consent. 

Please review app behavior to ensure compliance with these policies before midnight Coordinated Universal Time (UTC) on February 4, 2024. If your app contains policy violations, we may subject it to additional at any time, including from Removal from the Play Store and ban on publishing newly submitted apps.

What I want to know is, how can I solve this Google play review issue? Can upgrading the sdk version solve this problem?

**Comment by prof18** [comment] 2023-12-18 08:24
@powerzd The discussion for the same issue is going on here https://github.com/paypal/android-checkout-sdk/issues/281

**Comment by chpypl** [comment] 2024-01-09 17:26
Closed as duplicate of #281

**Closed by chpypl** 2024-01-09 17:26 UTC
Labels: 🐞 bug
