### ISSUE TITLE
Unable to build the app with Gradle plugin 7.0.3. when the checkout sdk is added

### ISSUE THREAD

**Issue by Krleblok94** [paypal/android-checkout-sdk#67] opened 2021-11-12 21:15 UTC
When you have the Android Gradle plugin version 7.0.2 or 7.0.3 and targeting Android 12 (compileSdkVersion = 31 and targetSdkVersion = 31 in the app Gradle file), the manifest merging when building the app fails due to some Activities with intent filters don't have explicitly set the exported attribute in the checkout SDK's manifest file.

1. Update gradle plugin version to 7.0.2 or 7.0.3
2. Set compileSdkVersion and targetSdkVersion in your app's gradle file to 31
3. Add the checkout sdk dependency as described in the PayPal docs or in quickstart sample app.
4. Try to build you app on a device or emulator targeting Android 11 or 12 (API 30 or 31)

**Expected behavior**
The app should build and install.

**Smartphone (please complete the following information):**
 - Android Version: API 30, API 31
 - Device: Any device or emulator with Android 11 (30) or Android 12 (31)
 - SDK Version [e.g. 0.5.1]

**Comment by tdchow** [comment] 2021-11-17 15:01
Hey @Krleblok94 - Thanks for reporting this. Our team will be picking up this work shortly. Android API 31 support will be in the next release of the SDK. Will keep you updated here.

**Comment by Mad-Bones** [comment] 2021-12-29 06:04
im getting this error: `Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.` 
after i added  `implementation 'com.paypal.checkout:android-sdk:0.5.2'`
on android studio. 

Expected behavior
The app should build and install.

Smartphone:

Android Version: API 31
Device: Any device or emulator with Android 12 (31)
SDK Version 0.5.2

¿is this allready solved? ¿what i'm doing wrong? all my activities are exported. mi project whas already migrated to androidx...

**Comment by tdchow** [comment] 2022-01-04 18:45
Hey @Mad-Bones - we're still in the progress of updating the SDK to target Android 12. For the time being, you won't be able to import the Checkout SDk and have your app target Android 12. We hope to have a new version released later this month. Will keep you updated.

**Comment by elkarry** [comment] 2022-02-02 07:38
@tdchow Any news on the release to support Android 12? An update was released last week but still no Android 12 support.

**Comment by tdchow** [comment] 2022-02-02 15:19
Hey @elkarry - Sorry for the delay. The Android 12 work is still underway and should be in the next SDK release.

**Comment by tdchow** [comment] 2022-02-16 22:07
Hey @Krleblok94, @Mad-Bones, and @elkarry!

Good news! We just released version 0.6.0 of the Checkout SDK which now targets Android 12.

```implementation 'com.paypal.checkout:android-sdk:0.6.0'```

@Krleblok94 - once you've verified the new version, would you be able to close out this issue? Thanks!

**Comment by tdchow** [comment] 2022-03-10 20:33
Closing due to inactivity, but the issue should be resolved in the latest SDK version.

**Closed by tdchow** 2022-03-10 20:33 UTC
Labels: 🐞 bug
