### ISSUE TITLE
How to clear previous user paypal data?

### ISSUE THREAD

**Issue by Oooooori** [paypal/android-checkout-sdk#195] opened 2023-02-02 13:51 UTC
Example:

Step 0: Initial state
App User: nil
Paypal User: nil

Step 1: User A logs into the app
App User: A
Paypal User: nil

Step 2: User A logs into their Paypal Checkout
App User: A
Paypal User: A

Step 3: User A logs out of the app
App User: nil
Paypal User: A

Step 4: User B logs into the app
App User: B
Paypal User: A

Step 5: User B goes to Paypal checkout and is able to use User A's Paypal.
App User: B
Paypal User: A

And in iOS SDK, I can call Checkout.logoutUser()
how to logout user in android sdk???

**Comment by saperi22** [comment] 2023-02-08 19:22
@Oooooori apologies for the delayed reply.
The logout functionality is slated to be available in our next release.

**Comment by tdchow** [comment] 2023-03-15 15:43
Closing this issue as it's a duplicate of https://github.com/paypal/android-checkout-sdk/issues/99

The changes are already merged for programmatic logout. It will be in the next release.

**Closed by tdchow** 2023-03-15 15:43 UTC
Labels: 🐞 bug
