### ISSUE TITLE
DK: Paypal Data Collector com.paypal.android.sdk:data-collector (consider upgrading to version com.braintreepayments.api:data-collector:3.21.0)

### ISSUE THREAD

**Issue by ImVeryGood** [paypal/android-checkout-sdk#312] opened 2024-02-23 09:14 UTC
I received a warning from Google with the following restrictions:
n the alternative, you may consider removing the SDK code designed to collect personal and sensitive user data by default, or moving to an alternative SDK or version which includes the appropriate technical mechanism to ensure that end user consent information collected by apps is honored. You may consider upgrading to a policy-compliant version of this SDK, if available from your SDK provider or removing the SDK. Google is unable to endorse or recommend any third party software.
Paypal Data Collector com.paypal.android.sdk:data-collector: Consider upgrading to version com.braintreepayments.api:data-collector:3.21.0 of the SDK.

**Comment by chpypl** [comment] 2024-03-21 16:56
Please see our update here https://github.com/paypal/android-checkout-sdk/issues/307#issuecomment-2012415922

Closing as a duplicate of #307

**Closed by chpypl** 2024-03-21 16:56 UTC
